# Generated by Django 4.1.1 on 2022-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_title_post_caption_remove_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
