# Generated by Django 4.1.1 on 2022-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Adidas", "Adidas"),
                    ("New Balance", "New Balance"),
                    ("Nike", "Nike"),
                ],
                default="Nike",
                max_length=20,
            ),
        ),
    ]
